add helm component

diff --git a/.github/workflows/firstflow.yml b/.github/workflows/firstflow.yml
--- a/.github/workflows/firstflow.yml
+++ b/.github/workflows/firstflow.yml
@@ -38,9 +38,9 @@ jobs:
       - name: create service
         run: kubectl apply -f hw-svc.yml -n homework
 
-  check:
-    needs: deploy
-    runs-on: self-hosted
-    steps:
-      - name: check curl
-        run: HTTP_RESULT=$(curl -i localhost:80 2>/dev/null |grep HTTP|awk '{print $2}' ); if [ "$HTTP_RESULT" = '200' ];then echo "deployed successful";exit 0; else echo "deployed failed";exit 255;fi
+          #check:
+          #needs: deploy
+          #runs-on: self-hosted
+          #steps:
+          # - name: check curl
+          #run: HTTP_RESULT=$(curl -i localhost:80 2>/dev/null |grep HTTP|awk '{print $2}' ); if [ "$HTTP_RESULT" = '200' ];then echo "deployed successful";exit 0; else echo "deployed failed";exit 255;fi
